### PR TITLE
ValidatingAdmissionPolicy for C-0076

### PR DESCRIPTION
**Pull request by suhasgumma**
### Control Rego: https://github.com/kubescape/regolibrary/blob/master/rules/label-usage-for-resources/raw.rego

### CODE REVIEW

**Comment by suhasgumma** [comment]
Hi @slashben, I could not integrate the following test cases as we are `using labels to bind` the `ValidatingAdmissionPolicy`
* Pod/ Deployment without labels is denied.
* Pod/Deployment with labels only from the configured list is allowed.

I have tested these cases manually and they are working as expected.

**Comment by slashben** [comment]
I will look into this

**Comment by slashben** [comment]
@suhasgumma , if we (for this control) create a test where the policy is bound via namespace (and not Pod/Deployment), would it work?

**Comment by suhasgumma** [comment]
> @suhasgumma , if we (for this control) create a test where the policy is bound via namespace (and not Pod/Deployment), would it work?

Hi @slashben , It would work if we bind them using a namespace. I will update it.

**Review by slashben — APPROVED** [review]

**Pull request merged**
