### PR TITLE
Updating documentation to be in up-to-date with 1.28

### PR DESCRIPTION
**Pull request by slashben**

### CODE REVIEW

**Review by kranurag7 — COMMENTED** [review]
@slashben How about adding config for [kind](https://kind.sigs.k8s.io/) users as well? 
```bash
cat <<EOF > cluster.yaml
kind: Cluster
name: test-cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "ValidatingAdmissionPolicy": true
runtimeConfig:
  "admissionregistration.k8s.io/v1alpha1": true
nodes:
- role: control-plane
  image: kindest/node:v1.27.3 # change this if required
EOF
kind create cluster --config=cluster.yaml
```

**Comment by slashben** [comment]
@kranurag7 do you have an example for 1.28?

**Comment by kranurag7** [comment]
Yes, for 1.28 I changed the version of the [image](https://hub.docker.com/r/kindest/node/tags) and updated `v1beta1` in admissionregistration api. Beta features are enabled to default so removed featureGates field from the above manifest. 
```yaml
cat <<EOF > cluster.yaml
kind: Cluster
name: test-cluster
apiVersion: kind.x-k8s.io/v1alpha4
runtimeConfig:
  "admissionregistration.k8s.io/v1beta1": true
nodes:
- role: control-plane
  image: kindest/node:v1.28.0
EOF

kind create cluster --config=cluster.yaml
```

**Comment by slashben** [comment]
> Yes, for 1.28 I changed the version of the [image](https://hub.docker.com/r/kindest/node/tags) and updated `v1beta1` in admissionregistration api. Beta features are enabled to default so removed featureGates field from the above manifest.
> 
> ```yaml
> cat <<EOF > cluster.yaml
> kind: Cluster
> name: test-cluster
> apiVersion: kind.x-k8s.io/v1alpha4
> runtimeConfig:
>   "admissionregistration.k8s.io/v1beta1": true
> nodes:
> - role: control-plane
>   image: kindest/node:v1.28.0
> EOF
> 
> kind create cluster --config=cluster.yaml
> ```

Sorry for the very late reply, added it, thanks!!

**Pull request merged**
